import { readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const generated = join(root, "src", "generated");
const file = join(generated, "schema.ts");
let source = readFileSync(file, "utf8");

const tsvectorBefore = source;
source = source.replace(
  /^\s*\/\/ TODO: failed to parse database type 'tsvector'\n(\s*)(\w+): unknown\("(\w+)"\)/gm,
  '$1$2: tsvector("$3")',
);
if (source !== tsvectorBefore && !source.includes('from "../types"')) {
  source = `import { tsvector } from "../types";\n${source}`;
}

// A foreign key the SQL adds with ALTER TABLE after both tables exist closes a reference
// cycle. drizzle-kit emits it as a table-level foreignKey(), which makes TypeScript infer the
// two tables from each other (TS7022). A column-level references() with an explicit
// AnyPgColumn return type breaks the cycle, which is what drizzle emits for self-references.
const camel = (s) => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
const migrationsDir = join(root, "migrations");
const alterPattern =
  /ALTER TABLE (\w+)\s+ADD CONSTRAINT \w+\s+FOREIGN KEY \((\w+)\)\s+REFERENCES (\w+)\((\w+)\)/gs;
const cyclic = [];
for (const name of readdirSync(migrationsDir)
  .filter((n) => n.endsWith(".sql"))
  .sort()) {
  const sql = readFileSync(join(migrationsDir, name), "utf8");
  for (const m of sql.matchAll(alterPattern)) {
    cyclic.push({
      table: camel(m[1]),
      column: camel(m[2]),
      sqlColumn: m[2],
      target: camel(m[3]),
      targetColumn: camel(m[4]),
    });
  }
}

let rewritten = 0;
const skipped = [];
for (const { table, column, sqlColumn, target, targetColumn } of cyclic) {
  const tableStart = source.indexOf(`export const ${table} = pgTable(`);
  if (tableStart < 0) {
    skipped.push(`${table}.${column}`);
    continue;
  }
  const tableEnd = source.indexOf("\n]);", tableStart);
  const block = source.slice(tableStart, tableEnd);
  const blockPattern = new RegExp(
    `\\s*foreignKey\\(\\{\\s*columns: \\[table\\.${column}\\],\\s*foreignColumns: \\[${target}\\.${targetColumn}\\],\\s*name: "[^"]+"\\s*\\}\\)(?:\\.[a-zA-Z]+\\([^)]*\\))*,?`,
  );
  const columnPattern = new RegExp(`(\\t${column}: uuid\\("${sqlColumn}"\\))`);
  if (!blockPattern.test(block) || !columnPattern.test(block)) {
    skipped.push(`${table}.${column}`);
    continue;
  }
  const patched = block
    .replace(blockPattern, "")
    .replace(columnPattern, `$1.references((): AnyPgColumn => ${target}.${targetColumn})`);
  source = source.slice(0, tableStart) + patched + source.slice(tableEnd);
  rewritten += 1;
}

source = `// generated by drizzle-kit pull, patched by scripts/postpull.mjs; never edit by hand\n${source}`;
writeFileSync(file, source);
rmSync(join(generated, "meta"), { recursive: true, force: true });
for (const stale of readdirSync(generated).filter((n) => n.endsWith(".sql"))) {
  rmSync(join(generated, stale), { force: true });
}
console.error(
  `postpull: tsvector ${source === tsvectorBefore ? "unchanged" : "patched"}, ${rewritten}/${cyclic.length} cyclic foreign keys rewritten${skipped.length ? `, skipped: ${skipped.join(", ")}` : ""}`,
);
